package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.46

import (
	"context"

	"github.com/lakhansamani/cloud-container/graph/model"
)

// Signup is the resolver for the signup field.
func (r *mutationResolver) Signup(ctx context.Context, params model.SignUpRequest) (*model.Response, error) {
	return r.Service.Signup(ctx, params)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, params model.LoginRequest) (*model.Response, error) {
	return r.Service.Login(ctx, params)
}

// VerifyOtp is the resolver for the verify_otp field.
func (r *mutationResolver) VerifyOtp(ctx context.Context, params model.VerifyOtpRequest) (*model.AuthResponse, error) {
	return r.Service.VerifyOTP(ctx, params)
}

// CreateDeployment is the resolver for the create_deployment field.
func (r *mutationResolver) CreateDeployment(ctx context.Context, params *model.CreateDeploymentRequest) (*model.Deployment, error) {
	return r.Service.CreateDeployment(ctx, params)
}

// DeleteDeployment is the resolver for the delete_deployment field.
func (r *mutationResolver) DeleteDeployment(ctx context.Context, params *model.DeleteDeploymentRequest) (*model.Response, error) {
	return r.Service.DeleteDeployment(ctx, params)
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (*model.Response, error) {
	return r.Service.Logout(ctx)
}

// Session is the resolver for the session field.
func (r *queryResolver) Session(ctx context.Context) (*model.AuthResponse, error) {
	return r.Service.Session(ctx)
}

// Deployments is the resolver for the deployments field.
func (r *queryResolver) Deployments(ctx context.Context, params *model.ListDeploymentsRequest) ([]*model.Deployment, error) {
	return r.Service.Deployments(ctx, params)
}

// Deployment is the resolver for the deployment field.
func (r *queryResolver) Deployment(ctx context.Context, params *model.GetDeploymentRequest) (*model.Deployment, error) {
	return r.Service.Deployment(ctx, params)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
